name             'ireport'
maintainer       'Pablo Fonseca'
maintainer_email 'pabloramon21@gmail.com'
license          'All rights reserved'
description      'Installs/Configures ireport'
long_description 'Installs/Configures ireport'
version          '0.1.0'
