name             'ireport'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ireport'
long_description 'Installs/Configures ireport'
version          '0.1.0'
